name:                icfpc2018
version:             0.1.0.0
github:              "ForNeVer/icfpc-2018"
license:             BSD3
author:              "CodingTeam"
maintainer:          "example@example.com"
copyright:           "2018 CodingTeam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ForNeVer/icfpc-2018#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- bits
- bytes
- binary
- bytestring
- bitwise
- containers

library:
  source-dirs: src

executables:
  icfpc2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - icfpc2018

tests:
  icfpc2018-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2018
    - tasty
    - tasty-hunit
